### ISSUE TITLE
Score output of Neural Network

### ISSUE THREAD

**Issue by irleader** [keio-bioinformatics/mxfold2#2]
Hi Dr Kengo Sat,

Please let me know if raising issues here about MXFold2 bothers you. I do have a lot of problem when trying to understand MXFold2 and apply it myself. I can email you if you think that's more appropriate.

This issue is about zuker.py(https://github.com/keio-bioinformatics/mxfold2/blob/master/mxfold2/fold/zuker.py) and Fig. 2 The network structure of our algorithm from you paper published on Nature Communications.

Assuming we using --model MixC and --pair-join cat:
1. From Fig .2 there are four types of score outputs, Helix Stacking, Unpaired Region, Helix Opening and Helix Closing, while zuker.py line 103-113, there are 10 scores (all of shape L *L). I can see score_helix_stacking should be Helix Stacking (first dimension of score_paired), how about score_basepair(all zeros), four types of score_mismatch (second dimension of score_paired) and four types of score_base (third dimension of score_paired)?  
2. There are also 7 other scores from line 39-45, can you explain a bit about them as well?I can't find any matches from Fig. 2.

Thanks a lot in advance.

**Comment by satoken** [comment]
1. score_helix_stacking corresponds to Helix Stacking. score_mismatch_* corresponds to Helix Opening and Helix Closing for upper and lower triangles. score_base_* corresponds to Unpaired Region. Unpaired Region.

2.  These are the scores related to the loop length. Although not mentioned in the paper, they are also used in CONTRAfold, which improves the prediction accuracy slightly.

Thanks,
