### ISSUE TITLE
Difficulty replicating webserver results using command line 

### ISSUE THREAD

**Issue by rjandr** [keio-bioinformatics/mxfold2#3]
What method is used for predicting structures on the webserver? As it is not detailed anywhere, I have tried several different models to predict RNA structures using the command line tool, but can not find a way to replicate the results I get from the webserver.

I am using different variations of the command `mxfold2 predict @./different_models.conf sequence.fasta`  

Is there a .conf file I can point to which will replicate webserver results?

Thanks

**Comment by satoken** [comment]
Thank you for your interest in mxfold2.

The web server uses mxfold2/mxfold2/models/TrainSetAB.conf, which is included in the source tree.

Thanks,

**Comment by rjandr** [comment]
I have just re-tried that .conf file but still cannot replicate my webserver result.

Here are my results from the webserver:
![image](https://user-images.githubusercontent.com/33700205/117743303-28bf4300-b1cc-11eb-97a4-15af0b14f753.png)

And here are my results using command line:
```
$ mxfold2 predict @./mxfold2-0.1.1/mxfold2/models/TrainSetAB.conf test.fasta 
>vegfa_region
GACTCTGCGCAGAGCACTTTGGGTCCGGAGGGCGAGACTCCGGCGGAAGCATTCCCGGGCGGGTGACCCAGCACGGTCCCTCTTGGAATTGGATTCGCCATTTTATTTTTCTTGCTGCTAAATCACCGAGCCCGGAAGATTAGAGAGTTTTATTTCTGGGATTCCTGTAGACACACCCACCCACATACATACATTTATATATATATATATTATATATATATAAAAATAAATATCTCTATTTTATATATATAAAATATATATATTCTTTTTTTAAATTAACAGTGCTAATGTTATTGGTGTCTTCACTGGATGTATTTGACTGCTGTGGACTTGAGTTGGGAGGGGAATGTTC
......((.....)).....(((..(((.(.......).)))((....))....(((((((((...((......)).)))..........((.....))..............................))))))......................(((...............))).))).......................................................................................................................................................................... (41.0)
```

**Comment by rjandr** [comment]
That works! Thanks
